name: GitHub Actions Deployment Demo
run-name: GitHub Actions Deployment Demo

# 觸發此 action 的時機
on:
  push:
    branches:  # 只要有任何一個 commit 被 push，就會觸發此 action
      '*'
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  deploy:
    name: deploy GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: build
        run: pnpm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist

      - run: echo '執行成功'
